### ISSUE TITLE
81.py revamp tracking

### ISSUE THREAD

**Issue by pinobatch** [pinobatch/little-things-nes#2]
- [ ] switch from deprecated optparse to maintained argparse, still handling `[-i] infile` manually because [argparse doesn't do that](https://stackoverflow.com/q/49058396/2738262)
- [ ] set the bias, or assumed $4011 level corresponding to 8-bit 128 or 16-bit 0
- [ ] DAC nonlinearity compensation
- [ ] apply low-pass filter during slope overload
- [ ] decoder option, where `-r` sets the output rate rather than the resampling rate
